name: Azimuth
main: rockbeatspaper.Azimuth.Azimuth
version: 0.2-SNAPSHOT
author: Bryanna Denney

commands:
  compassAdd:         
    description: Adds new compass points to rotation.
    alias: azimuthAdd
    usage: |
           /<command> personal spawn OR
           /<command> personal_spawn OR
           /<command> personalSpawn
    
  azimuth:
    description: Describes commands available with Azimuth plugin. 
    usage: /<command>
  
  compassRemove:
    description: Removes compass points from rotation.
    alias: azimuthRemove
    usage: |
           /<command> world spawn OR
           /<command> world_spawn OR
           /<command> worldSpawn 